### ISSUE TITLE
你好，运行项目项目报错如下

### ISSUE THREAD

**Issue by JserJser** [wangzilaogong/Vuebackend#2]
![image](https://user-images.githubusercontent.com/30041386/59217255-1c04cf80-8bf0-11e9-9315-e02cb8281f4e.png)

**Comment by wangzilaogong** [comment]
你可以把router 下index.js里面的相关引用删除


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: jser_dimple <notifications@github.com>
发送时间: 2019年6月11日 02:25
收件人: wangzilaogong/Vuebackend <Vuebackend@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[wangzilaogong/Vuebackend] 你好，运行项目项目报错如下 (#2)

**Comment by JserJser** [comment]
你好，
![image](https://user-images.githubusercontent.com/30041386/59235833-f98da900-8c25-11e9-8bec-70373ced21e5.png)

**Comment by JserJser** [comment]
cnpm run dev 报错如下
![image](https://user-images.githubusercontent.com/30041386/59235856-11652d00-8c26-11e9-8a98-b6862cf490a4.png)

**Comment by JserJser** [comment]
介意我加你qq吗？看到了qq邮箱。现在在做一个i18n的功能，做不完不下班那种

**Comment by wangzilaogong** [comment]
这些依赖都去掉哈 store的没啥用


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: jser_dimple <notifications@github.com>
发送时间: 2019年6月11日 08:51
收件人: wangzilaogong/Vuebackend <Vuebackend@noreply.github.com>
抄送: wukai <997972547@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[wangzilaogong/Vuebackend] 你好，运行项目项目报错如下 (#2)




cnpm run dev 报错如下

**Comment by JserJser** [comment]
我根据你说的修改
![image](https://user-images.githubusercontent.com/30041386/59237499-21ccd600-8c2d-11e9-913f-05e891f8279e.png)
![image](https://user-images.githubusercontent.com/30041386/59237511-2f825b80-8c2d-11e9-93fd-811df8eba741.png)

![image](https://user-images.githubusercontent.com/30041386/59237517-36a96980-8c2d-11e9-89b3-2b249588347f.png)

**Comment by wangzilaogong** [comment]
把路路由配置最后一个对象去掉


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: jser_dimple <notifications@github.com>
发送时间: 2019年6月11日 09:42
收件人: wangzilaogong/Vuebackend <Vuebackend@noreply.github.com>
抄送: wukai <997972547@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[wangzilaogong/Vuebackend] 你好，运行项目项目报错如下 (#2)




我根据你说的修改
